"""empty message

Revision ID: 535384e599d2
Revises: 3dece180622f
Create Date: 2021-10-04 22:50:05.692917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '535384e599d2'
down_revision = '3dece180622f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vaccination_model', sa.Column('total_number', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vaccination_model', 'total_number')
    # ### end Alembic commands ###
